name: xftts
description: A simple library for Xunfei TTS websocket API.
version: 0.1.2
homepage: https://github.com/tyrchen/xftts-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: '>=2.1.4 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
